---
- name: check for ssh
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for readiness
      wait_for:
        port: 22
        host: '{{ ansible_host }}'
        search_regex: OpenSSH
        delay: 5
      connection: local

- name: install Prometheus
  hosts: all
  become: yes
#  vars:
#    pip_install_packages:
#      - name: docker
  roles:
    - cloudalchemy.prometheus
    - geerlingguy.docker
  tasks:
    - name: Install pip3
      apt:
        name:
          - python3-pip
    - name: Install pip docker
      pip:
        name: docker
    - name: Run containter
      docker_container:
        name: whoami
        image: bee42/whoami:2.1.0
        state: started
        ports:
          - "9292:80"
