---
- name: check for ssh
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for readiness
      wait_for:
        port: 22
        host: '{{ ansible_host }}'
        search_regex: OpenSSH
        delay: 5
      connection: local

- name: install Prometheus
  hosts: all
  become: yes
  roles:
    - geerlingguy.mysql
    - cloudalchemy.prometheus
    - cloudalchemy.mysqld_exporter
