---
- name: check for ssh
  hosts: all
  gather_facts: no
  tasks:
    - name: check ssh state
      wait_for:
        port: 22
        host: '{{ ansible_host }}'
        search_regex: OpenSSH
        delay: 5
      connection: local

- name: install Prometheus
  hosts: server1
  become: yes
  roles:
    - cloudalchemy.prometheus
    - cloudalchemy.node_exporter
    - idealista.timescaledb_role
