---
- name: check for ssh
  hosts: all
  gather_facts: no
  tasks:
    - name: check ssh state
      wait_for:
        port: 22
        host: '{{ ansible_host }}'
        search_regex: OpenSSH
        delay: 5
      connection: local

- name: install Prometheus
  hosts: all
  become: yes
  roles:
    - cloudalchemy.prometheus
    - cloudalchemy.node_exporter
  tasks:
    - name: link alerts.yml
      file:
        src: /opt/prometheus/rules/ansible_managed.rules
        dest: /opt/prometheus/alerts.yml
        owner: monitoring
        group: monitoring
        state: link
