---
- name: check for ssh
  hosts: all
  gather_facts: no
  tasks:
    - name: check ssh state
      wait_for:
        port: 22
        host: '{{ ansible_host }}'
        search_regex: OpenSSH
        delay: 5
      connection: local

- name: install Prometheus
  hosts: all
  become: yes
  roles:
    - cloudalchemy.prometheus
    - cloudalchemy.node_exporter

- name: copy queries
  hosts: server1
  tasks:
    - name: task 1
      copy:
        src: files/task1.txt
        dest: /tmp/query1.txt
    - name: task 2
      copy:
        src: files/task2.txt
        dest: /tmp/query2.txt
