#
# Ansible managed
#
# http://prometheus.io/docs/operating/configuration/

global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s

  external_labels:
    environment: s2




rule_files:
  - /opt/prometheus/rules/*.rules


scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets:
      - s2:9090
  - job_name: node-exporter
    static_configs:
    - targets:
      - 192.168.33.10:9100
      - 192.168.33.11:9100
  - job_name: cadvisor
    static_configs:
    - targets:
      - 192.168.33.10:8080
  - job_name: mysqld
    static_configs:
    - targets:
      - 192.168.33.10:9104
